/* confdefs.h */
#define PACKAGE_NAME "libdill"
#define PACKAGE_TARNAME "libdill"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "libdill 1.0"
#define PACKAGE_BUGREPORT "libmill@freelists.org"
#define PACKAGE_URL "http://libdill.org/"
#define PACKAGE "libdill"
#define VERSION "1.0"
#define DILL_THREADS 1
#define DILL_PTHREAD 1
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_MPROTECT 1
#define DILL_NO_EPOLL 1
#define HAVE_KQUEUE 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define DILL_SHARED 1
